import { ProgramFilterGroup, UniversityListItem } from 'types/university';

export const PROGRAM_TABS: ProgramFilterGroup[] = [
  {
    key: 'executive',
    label: 'Executive Programs',
    options: [
      'Executive MBA',
      'Dual MBA',
      'Online MBA',
      'MA',
      'M.Sc',
      'M.Tech',
      'MCA',
      'Distance MBA',
      'MCom',
      'PGDM',
      'PGDM (Ex)',
      'PGDBA',
      'LLM',
      '1‑Year Online MBA',
    ],
  },
  {
    key: 'pg',
    label: 'PG Courses',
    options: ['MBA', 'MCA', 'M.Tech', 'M.Sc', 'MA'],
  },
  {
    key: 'ug',
    label: 'UG Courses',
    options: ['BBA', 'BCA', 'B.Tech', 'B.Com', 'BA'],
  },
];

export const UNIVERSITIES: UniversityListItem[] = [
  {
    slug: 'dr-dy-patil-vidyapeeth',
    name: 'Dr. D.Y. Patil Vidyapeeth University',
    city: 'Pune',
    approvals: ['AICTE', 'NAAC', 'NIRF', 'UGC', 'WES'],
    rating: 4.5,
    logo: '/assets/logos/dypu.png',
    image: '/assets/images/universities/dypu.jpg',
    prospectusUrl: '#',
  },
  {
    slug: 'nmims-university',
    name: 'NMIMS University',
    city: 'Mumbai',
    approvals: ['AICTE', 'ARIIA', 'ISO', 'UGC', 'NBA', 'NIRF'],
    rating: 4.5,
    logo: '/assets/logos/nmims.png',
    image: '/assets/images/universities/nmims.jpg',
    prospectusUrl: '#',
  },
  {
    slug: 'jain-university',
    name: 'Jain University',
    city: 'Bengaluru',
    approvals: ['AICTE', 'NIRF', 'ISO', 'UGC', 'NBA', 'NAAC'],
    rating: 4.5,
    logo: '/assets/logos/jain.png',
    image: '/assets/images/universities/jain.jpg',
    prospectusUrl: '#',
  },
  {
    slug: 'dy-patil-navi-mumbai',
    name: 'Dr. D.Y. Patil Navi Mumbai',
    approvals: ['AICTE', 'NAAC', 'NBA', 'UGC', 'WES'],
    rating: 4.5,
    logo: '/assets/logos/dypu.png',
    image: '/assets/images/universities/dypu-navi.jpg',
    prospectusUrl: '#',
  },
  {
    slug: 'goa-institute-of-management',
    name: 'Goa Institute of Management',
    approvals: ['AACSB', 'AICTE', 'AIU', 'AMBA', 'NBA', 'SAQS'],
    rating: 4.5,
    logo: '/assets/logos/gim.png',
    image: '/assets/images/universities/gim.jpg',
    prospectusUrl: '#',
  },
  {
    slug: 'mdi-gurgaon',
    name: 'MDI Gurgaon',
    approvals: ['AICTE', 'NBA', 'NIRF', 'SAQS'],
    rating: 4.5,
    logo: '/assets/logos/mdi.png',
    image: '/assets/images/universities/mdi.jpg',
    prospectusUrl: '#',
  },
  {
    slug: 'imt-cdl',
    name: 'IMT CDL',
    approvals: ['AICTE', 'AIU', 'NAAC', 'NBA', 'NIRF', 'SAQS', 'UGC'],
    rating: 4.5,
    logo: '/assets/logos/imt.png',
    image: '/assets/images/universities/imt.jpg',
    prospectusUrl: '#',
  },
  {
    slug: 'deakin-business-school',
    name: 'Deakin Business School',
    approvals: ['AACSB', 'EQUIS'],
    rating: 4.5,
    logo: '/assets/logos/deakin.png',
    image: '/assets/images/universities/deakin.jpg',
    prospectusUrl: '#',
  },
  {
    slug: 'gla-university',
    name: 'GLA University',
    approvals: ['AICTE', 'NAAC', 'NIRF', 'UGC'],
    rating: 4.5,
    logo: '/assets/logos/gla.png',
    image: '/assets/images/universities/gla.jpg',
    prospectusUrl: '#',
  },
  {
    slug: 'kurukshetra-university',
    name: 'Kurukshetra University',
    approvals: ['NAAC', 'AICTE', 'NIRF', 'UGC'],
    rating: 4.5,
    logo: '/assets/logos/kuk.png',
    image: '/assets/images/universities/kurukshetra.jpg',
    prospectusUrl: '#',
  },
  {
    slug: 'mdi-gurgaon-alt',
    name: 'MDI Gurgaon',
    approvals: ['AICTE', 'ARIIA', 'NIRF'],
    rating: 4.5,
    logo: '/assets/logos/mdi.png',
    image: '/assets/images/universities/mdi-gurgaon.jpg',
    prospectusUrl: '#',
  },
  {
    slug: 'amity-university',
    name: 'Amity University',
    approvals: ['UGC', 'AICTE', 'NAAC'],
    rating: 4.5,
    logo: '/assets/logos/amity.png',
    image: '/assets/images/universities/amity.jpg',
    prospectusUrl: '#',
  },
];
